### ISSUE TITLE
cast problem with albatross data

### ISSUE THREAD

**Issue by mdsumner** [Maschette/SOmap#9]
Why?

```R
data("albatross", package = "adehabitatLT")
track <- rgdal::project(as.matrix(purrr::map_df(albatross, ~rbind(.x[c("x", "y")], NA))), "+proj=utm +zone=42 +south +datum=WGS84", inv = TRUE)
SOauto_map(track[,1], track[,2])
 Error in st_cast_sfc_default(x) : list item(s) not of class sfg 
```

**Comment by raymondben** [comment]
I think this is happening with any call to `SOauto_map`: on the first call, all is good, on second and subsequent calls, I see this error

**Comment by mdsumner** [comment]
Oh, perhaps a loading thing of sf. Explicit ::imports might fix

**Comment by mdsumner** [comment]
Fixed in https://github.com/Maschette/SOmap/commit/173d0fffbb4e03c24f5475513767a6d4e5741163  

(－‸ლ)
